/* Concatenates src/ into a single self-contained dist/index.html.
   No bundler and no imports: the deploy target is one HTML file with a strict
   CSP, so every byte must already be inside it. See
   docs/decisions/0002-single-file-build.md. */
/* ADR 0002: no bundler, no imports in src/ — plain scripts concatenated in
   manifest order. docs/decisions/0002-single-file-build.md */
import { readFile, writeFile, mkdir } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

/* ADR 0006: two targets, one manifest — the demo and the library.
   docs/decisions/0006-embeddable-agent-avatar.md */
const root = dirname(fileURLToPath(import.meta.url))
const src = (p) => join(root, 'src', p)
const demo = (p) => join(root, 'demos', p)

const manifest = JSON.parse(await readFile(src('manifest.json'), 'utf8'))
const parts = await Promise.all(manifest.map((p) => readFile(src(p), 'utf8')))
const head = await readFile(src('shell.html'), 'utf8')
const tail = await readFile(src('shell-tail.html'), 'utf8')

const out = head + '<script>' + parts.join('\n') + tail
await mkdir(join(root, 'dist'), { recursive: true })
await writeFile(join(root, 'dist', 'index.html'), out, 'utf8')
console.log(`built dist/index.html — ${manifest.length} modules, ${(out.length / 1024).toFixed(1)} KB`)

/* Second target: the creature on its own, as an ES module, for anyone
   embedding it in their own agent UI. Same sources, minus the demo page —
   the split is the manifest, so there is no second copy of anything and no
   way for the library build to drift from the one on the demo.

   Everything the sources declare stays inside the closure, which is what makes
   a file full of top-level `const`s safe to hand somebody else.
   ADR 0006: docs/decisions/0006-embeddable-agent-avatar.md

   That closure is emitted as a FACTORY, and this is where several live Motes
   come from. The sources are plain concatenated scripts: every creature helper
   reads the shared names `mote`, `clock`, `pending`, `epoch`, `anim`. Calling
   the factory again evaluates the whole file again and yields a second set of
   those names — a complete, isolated creature runtime — without a single
   helper having to learn what an instance is.

   `Mote.mount` therefore builds a fresh copy per call, so multi-instance is
   the plain behaviour of the documented API rather than a second entry point
   somebody has to know about. Everything else on the object is a pure lookup
   over ported constants, so it is served from one shared copy.
   ADR 0009: docs/decisions/0009-multi-instance-agent-avatars.md */
const NL = String.fromCharCode(10)
const core = manifest.filter((p) => !p.startsWith('app/'))
const coreParts = await Promise.all(core.map((p) => readFile(src(p), 'utf8')))
const lib = [
  '/* Mote — an avatar for an AI agent. MIT. Ported in part from Bloub',
  '   (MIT, (c) 2026 Jeremy Perret) — see NOTICE. Generated by build.mjs;',
  '   edit src/, not this file. */',
  '',
  '/* One independent copy of the creature runtime. See build.mjs and ADR 0009:',
  '   docs/decisions/0009-multi-instance-agent-avatars.md */',
  'const createMoteRuntime = () => {',
  coreParts.join(NL),
  '  return Mote;',
  '};',
  '',
  '/* The shared copy answers the pure lookups; every mount gets its own.',
  '   `describe` is a pure function of the name, so it stays shared too. */',
  'const shared = createMoteRuntime();',
  'const MoteLib = {',
  '  mount: (host, opts) => createMoteRuntime().mount(host, opts),',
  '  faces: shared.faces,',
  '  states: shared.states,',
  '  bodies: shared.bodies,',
  '  palette: shared.palette,',
  '  describe: shared.describe,',
  '};',
  '',
  'export default MoteLib;',
  'export { MoteLib as Mote };',
  '/* Escape hatch: a whole private copy of the library, for a host that wants',
  '   to own the lifetime itself. `Mote.mount` already does this per call. */',
  'export { createMoteRuntime };',
  '',
].join(NL)
await writeFile(join(root, 'dist', 'mote-avatar.js'), lib, 'utf8')
await writeFile(join(root, 'dist', 'mote-avatar.d.ts'),
  await readFile(src(join('embed', 'types.d.ts')), 'utf8'), 'utf8')
console.log(`built dist/mote-avatar.js — ${core.length} modules, ${(lib.length / 1024).toFixed(1)} KB, + types`)

/* A second, integration-shaped demo. It consumes the generated public module
   exactly like a host application, so its workflow cannot reach internals. */
const actionsDemo = await readFile(demo('github-actions.html'), 'utf8')
await writeFile(join(root, 'dist', 'github-actions.html'), actionsDemo, 'utf8')
console.log(`built dist/github-actions.html — scripted agent workflow demo`)
