/* ── DECOR ────────────────────────────────────────────────────────────────
   Everything the animations draw that is not the creature: the orbit rings,
   the swoosh, the three thinking dots, the burst particles, the comet ribbons
   and the notification pip.

   Ported from bloub/src/bot/decor.ts, constants included. The seeded tables
   (RINGS, SWOOSH, COMET_RIBBONS, PARTICLES) are generated by the same PRNG
   from the same seeds in the same order, so they come out identical — which is
   the only reason it is safe to keep them as code rather than as data.       */
/* ADR 0005: ported verbatim; the rings and ribbons are seeded tables and the
   draw order is load-bearing. docs/decisions/0005-animation-catalogue.md */

/* The rings are not flat colours: a full hue wheel at constant lightness,
   with a gradient along each stroke. Measured S 45-62%, L 50-67%. */
function wheel(hue, s = 0.55, l = 0.62) {
  const h = ((hue % 360) + 360) % 360;
  const c = (1 - Math.abs(2 * l - 1)) * s;
  const x = c * (1 - Math.abs(((h / 60) % 2) - 1));
  const m = l - c / 2;
  const rgb =
    h < 60 ? [c, x, 0] : h < 120 ? [x, c, 0] : h < 180 ? [0, c, x]
      : h < 240 ? [0, x, c] : h < 300 ? [x, 0, c] : [c, 0, x];
  const hex = (v) => Math.round((v + m) * 255).toString(16).padStart(2, "0");
  return `#${hex(rgb[0])}${hex(rgb[1])}${hex(rgb[2])}`;
}

/* An inclined 3D circle in orthographic projection.

   The z component is not decoration: it splits the stroke in two, and the half
   with z < 0 is drawn BEFORE the body so the body occludes it. That real depth
   sort is what makes the rings read as orbits rather than as a flat doodle. */
function arcRender(seed, t, scale, id, opacity = 1) {
  const spin = seed.phase + t * seed.speed * TAU;
  const cu = Math.cos(seed.tilt), su = Math.sin(seed.tilt);
  const kz = Math.sqrt(Math.max(0, 1 - seed.k * seed.k));

  const N = 64;
  const span = seed.sweep * TAU;
  let front = "", back = "", prev = null;

  for (let i = 0; i <= N; i++) {
    const th = spin + (i / N) * span;
    const ct = Math.cos(th), st = Math.sin(th);
    const x = seed.a * (ct * cu + st * -su * seed.k) + seed.cx;
    const y = seed.a * (ct * su + st * cu * seed.k) + seed.cy;
    const z = seed.a * st * kz;
    const behind = z < 0;
    const cmd = behind !== prev ? "M" : "L";
    if (behind) back += `${cmd}${r2(x * scale)} ${r2(y * scale)}`;
    else front += `${cmd}${r2(x * scale)} ${r2(y * scale)}`;
    prev = behind;
  }

  const gx = cu * seed.a * scale, gy = su * seed.a * scale;
  return {
    id, front, back, width: seed.width * scale, opacity,
    grad: {
      x1: r2(seed.cx * scale - gx), y1: r2(seed.cy * scale - gy),
      x2: r2(seed.cx * scale + gx), y2: r2(seed.cy * scale + gy),
      stops: [wheel(seed.hue), wheel(seed.hue + seed.hueSpan * 0.5), wheel(seed.hue + seed.hueSpan)],
    },
  };
}

const RING_RNG = createRng(0xa11ce);
/* Six rings, semi-major 1.30-1.40 — comfortably larger than the ball —
   flattening always <= 0.45, ~3.3 turns a second. */
const RINGS = Array.from({ length: 6 }, (_, i) => ({
  a: 1.3 + RING_RNG() * 0.1,
  k: 0.05 + RING_RNG() * 0.4,
  tilt: (i / 6) * Math.PI + RING_RNG() * 0.5,
  speed: 3 + RING_RNG() * 0.7,
  phase: RING_RNG() * TAU,
  sweep: 0.6 + RING_RNG() * 0.25,
  hue: (i * 360) / 6 + RING_RNG() * 30,
  hueSpan: 60 + RING_RNG() * 60,
  width: 0.05 + RING_RNG() * 0.012,
  cx: 0, cy: 0.1,
}));

/* Nested arcs sweeping across the triangle, seen almost edge-on. */
const SWOOSH = Array.from({ length: 4 }, (_, i) => ({
  a: 0.78 + i * 0.2, k: 0.05 + i * 0.02, tilt: -0.62 + i * 0.05,
  speed: 0.3, phase: 0.06 * i, sweep: 0.4,
  hue: 95 + i * 62, hueSpan: 100, width: 0.05, cx: 0, cy: -0.12,
}));

/* Three dots: measured x, y = 0. */
const DOT_X = [-0.557, -0.013, 0.532];
const DOT_R = 0.165;
const DOT_PEAK = 1.25;

const P_RNG = createRng(0xbeef);
/* Five particles, one born every 0.2s, life 0.55s. */
const PARTICLES = Array.from({ length: 5 }, (_, i) => ({
  birth: i * 0.2, angle: P_RNG() * TAU, rho: 0.58 + P_RNG() * 0.18,
}));

/* They do not fly straight out: they spiral inward (radius x0.75 a frame,
   angle +100deg/s) while growing, and pass behind the core to be swallowed. */
function particles(t, scale) {
  const out = [];
  for (const p of PARTICLES) {
    const u = t - p.birth;
    if (u < 0 || u > 0.62) continue;
    const rho = p.rho * Math.pow(0.75, u * 10);
    const a = p.angle + (u * 100 * Math.PI) / 180;
    out.push({
      x: Math.cos(a) * rho * scale,
      y: Math.sin(a) * rho * scale,
      r: (0.04 + 0.028 * clamp(u / 0.55)) * scale,
      depth: clamp(1 - rho / 0.8),
      opacity: clamp(u / 0.06) * clamp((0.62 - u) / 0.08),
    });
  }
  return out;
}

/* The comet dot does not cross the screen: it stays put and the trail orbits
   it. Ellipse a 0.85, b 0.15, major axis +34deg, four ribbons, ~210deg/s. */
const COMET_RNG = createRng(0xc0e7);
const COMET_RIBBONS = Array.from({ length: 4 }, (_, i) => {
  const d = i - 1.5;
  return {
    a: 0.85 * (1 + d * 0.03),
    k: (0.15 / 0.85) * (1 + d * 0.16),
    tilt: (34 * Math.PI) / 180 + d * 0.035,
    speed: 210 / 360,
    phase: -i * 0.045 + COMET_RNG() * 0.012,
    sweep: 0.34, hue: i * 85 + COMET_RNG() * 20, hueSpan: 80,
    width: 0.095, cx: 0, cy: 0,
  };
});
const COMET_DOT = 0.129;

/* The notification pip sits exactly on the circumference, at -42deg, and the
   body is notched out concentrically around it with a constant margin. */
const NOTIF_BLUE = "#2496e8";
const NOTIF_ANGLE = -42;
const NOTIF_DIST = 1.003;
const NOTIF_R = 0.15;
const NOTIF_POP = 1.14;
const NOTIF_MARGIN = 0.054;
